version: '3.1'

services:
  postgres-server:
    build: .
    image: postgres:11-beta3-alpine
    restart: always
    ports:
    - 5432:5432
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 123
     POSTGRES_DB: avaliation  