CREATE TABLE product (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	price numeric(19,2) NULL,
	quantity int4 NULL,
	industry varchar(255) NULL,
	origin varchar(255) NULL,
	"type" varchar(255) NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id),
	CONSTRAINT uk_name UNIQUE (name)
)